CREATE DATABASE IF NOT EXISTS erp_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'ERPSYSTE';
GRANT ALL PRIVILEGES ON erp_db.* TO 'root'@'localhost';
FLUSH PRIVILEGES;
